In [6]:
import numpy as np
import time

## Definition 4

In [15]:
def subword_subset(a,n):
    
    split_list = []
    len_a = len(a)
    for i in range(len_a):
        delim = len_a - i
        if delim < n:
            break
        split_list.append(a[i:i+n]) 
    return split_list

def Omega(arr):

#     t0 = time.time()
    
    subword_set = []
    for i in range(1, len(arr)):
        subword_set.extend(subword_subset(arr, i))
    subword_set.append(arr)
    
#     t1 = time.time()
#     print("Total time elapsed: ", t1-t0)
    
    return subword_set

for i in range(10):
    Omega('001010')

In [17]:
Omega1 = Omega('001010')
print(Omega1)
Omega2 = Omega('002020')

['0', '0', '1', '0', '1', '0', '00', '01', '10', '01', '10', '001', '010', '101', '010', '0010', '0101', '1010', '00101', '01010', '001010']


## Previous implementation of Defn 4 
##### Note the difference in efficiency 

In [32]:
def subword_len(a,n=1):
    
    split_list = [a[i:i+n] for i in range(0, len(a), 1)]
    
    return [x  for x in split_list if len(x) == n and len(x)>0]

def subword(a):
    #t0 = time.time()
    try:
        b=[a]
        nmax=len(a)
        for n in range(nmax):
            c=subword_len(a,n)
            if len(c)>0:
                b=np.append(b,c)
        return b

    except: 
        return b

    #t1 = time.time()
    #print("Total time elapsed: ", t1-t0)

subword('34')
# for i in range(10):
#     print(subword('001010'))

array(['34', '3', '4'], dtype='|S2')

## Definition 5 - Jacard Similarity

##### Same as prior implementation as per ishanuc

In [7]:
def get_unweightedJac(S1,S2):
    return (len(set(S1).union(S2))-len(set(S1).intersection(S2)))/(0.0+len(set(S1).union(S2)))

# Definition 6 - Weighted Jacard Sequential Distance

In [7]:
def sum_weight_list(a):
    t0 = time.time()
    for i in range(len(a)):
        a[i]
    t1 = time.time()
   #print("list time: ", t1 - t0)
    return t1 - t0

def sum_weight_list_alt(a):
    t0 = time.time()
    for fish in a:
        fish
    t1 = time.time()
    #print("list alt time: ", t1 - t0)
    return t1 - t0
    
def sum_weight_set(a):
    t0 = time.time()
    for fish in a:
        fish
    t1 = time.time()
    #print("set time: ", t1 - t0)
    return t1 - t0

listtime = 0
listalttime = 0
settime = 0
for i in range(100):
    listtime += sum_weight_list(list(set(Omega1).union(Omega2)))
    listalttime += sum_weight_list_alt(list(set(Omega1).union(Omega2)))
    settime += sum_weight_set(set(Omega1).union(Omega2))

print("100 runs list: ", listtime)
print("100 runs list alt: ", listalttime)
print("100 runs set: ", settime)

('100 runs list: ', 0.0003724098205566406)
('100 runs list alt: ', 0.00019240379333496094)
('100 runs set: ', 0.0002491474151611328)


In [8]:
def get_weightedJac(S1,S2, sum_weight):
    sum_weight_union = sum_weight(list(set(S1).union(S2)))
    return (sum_weight_union - sum_weight(list(set(S1).intersection(S2))))/(0.0+sum_weight_union)

# Generate rando data

In [9]:
p0 = np.asarray([0.1, 0.05, 0.05, 0.2, 0.4, 0.2])
dummy = np.random.choice(np.arange(0, 6), size = (10,10),p = p0)
dummy

array([[4, 5, 1, 4, 3, 2, 1, 3, 4, 0],
       [4, 5, 4, 5, 4, 4, 3, 5, 5, 4],
       [1, 1, 4, 1, 4, 3, 4, 0, 3, 4],
       [3, 0, 3, 4, 4, 0, 5, 4, 0, 5],
       [2, 0, 4, 5, 3, 4, 3, 5, 4, 3],
       [4, 4, 4, 2, 3, 3, 2, 2, 5, 3],
       [3, 4, 5, 5, 2, 4, 0, 3, 0, 5],
       [4, 0, 3, 3, 5, 4, 4, 5, 4, 4],
       [4, 4, 2, 3, 4, 4, 4, 3, 0, 4],
       [4, 4, 5, 0, 4, 5, 3, 1, 5, 0]])

In [33]:
print(dummy[:,0].shape)

(50,)


In [45]:
# make sure to weight each sequence by population prevalence 
# (basically use the probability vector that we will be shifting around)
# Implement the weighted Jacard Later

def weight(p0_vector, i):
    return 1/p0_vector[i]

def jacMatrix(vec):
    length = vec.shape[0]
    jac_mat = np.zeros(shape = (length, length))
    print(vec[1])
    for i in range(length):
        for j in range(length):
            jac_mat[i][j] = get_unweightedJac(subword(vec[i]), subword(vec[j]))
    return jac_mat
                       
test_jac = jacMatrix(dummy)
test_jac
                       
                       
        
            
            

[3 5 2 4 5 5 1 5 5 4]


array([[0.        , 0.5       , 0.4       , 0.4       , 0.2       ,
        0.25      , 0.2       , 0.        , 0.4       , 0.2       ],
       [0.5       , 0.        , 0.2       , 0.2       , 0.33333333,
        0.4       , 0.33333333, 0.5       , 0.5       , 0.33333333],
       [0.4       , 0.2       , 0.        , 0.        , 0.2       ,
        0.25      , 0.2       , 0.4       , 0.66666667, 0.5       ],
       [0.4       , 0.2       , 0.        , 0.        , 0.2       ,
        0.25      , 0.2       , 0.4       , 0.66666667, 0.5       ],
       [0.2       , 0.33333333, 0.2       , 0.2       , 0.        ,
        0.4       , 0.        , 0.2       , 0.5       , 0.33333333],
       [0.25      , 0.4       , 0.25      , 0.25      , 0.4       ,
        0.        , 0.4       , 0.25      , 0.6       , 0.4       ],
       [0.2       , 0.33333333, 0.2       , 0.2       , 0.        ,
        0.4       , 0.        , 0.2       , 0.5       , 0.33333333],
       [0.        , 0.5       , 0.4      

# Quasi Metric

In [10]:
# reverse dictionary that assigns probability from original probability vector 
# to an index for use in next fn
def prob_reverse(prob_vec):
    rev_probs = {}
    for i in range(prob_vec.shape[0]):
        rev_probs[i] = prob_vec[i]
    return rev_probs

rev_dict = prob_reverse(p0)
rev_dict

{0: 0.1, 1: 0.05, 2: 0.05, 3: 0.2, 4: 0.4, 5: 0.2}

In [16]:
# reverse dictionary that assigns probability to indexed history
# we initialize this then we, in the future only edit the hist_prob_dict for future histories
def hist_probs(histories, prob_dict):
    hist_prob = {}
    for i in range(histories.shape[0]):
        hist_prob[i] = prob_dict[histories[i][0]]
    return hist_prob

hist_prob = hist_probs(dummy, rev_dict)
hist_prob

{0: 0.4,
 1: 0.4,
 2: 0.05,
 3: 0.2,
 4: 0.05,
 5: 0.4,
 6: 0.2,
 7: 0.4,
 8: 0.4,
 9: 0.4}

In [18]:
# quasi metric matrix normalization constant
def qm_matrix_normalization(hist_probs, i, j):
    return .5 * (((1/hist_probs[i]) + (1/hist_probs[j])) - 2)
test = qm_matrix_normalization(hist_prob, 1, 1)
test

1.5

In [48]:



# takes in jacard matrix and probabilty vector
# returns quasi metric matrix
# remember we have not used the weight fn, so this needs to be later implemented
# can combine later with jac_matrix maker so we dont have to do 2 runs of matrix
def qm_Matrix(vec, jac_mat, prob_vec):
    length = jac_mat.shape[0]
    qm_mat = np.zeros(shape = (length, length))
    for i in range(length):
        for j in range(length):
            qm_mat[i][j] = qm_matrix_normalization(prob_vec, vec[i], vec[j]) * jac_mat[i][j]
    return qm

test_qm = qm_Matrix(dummy, test_jac, p0)
test_qm

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
#